### ISSUE TITLE
feature: support gRPC Token-based authentication

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-authorize#27]
Per https://grpc.io/docs/guides/auth/#supported-auth-mechanisms, 

> Token-based authentication with Google: gRPC provides a generic mechanism (described below) to attach metadata based credentials to requests and responses. Additional support for acquiring access tokens (typically OAuth2 tokens) while accessing Google APIs through gRPC is provided for certain auth flows: you can see how this works in our code examples below. In general this mechanism must be used as well as SSL/TLS on the channel - Google will not allow connections without SSL/TLS, and most gRPC language implementations will not let you send credentials on an unencrypted channel.

This issue tracks the supporting of this mechanism.

Related: https://github.com/greenpau/caddy-auth-portal/issues/34

**Comment by greenpau** [comment]
@ joe-getcouragenow , the OAuth2.0 is now available in `caddy-auth-portal`. Please read https://github.com/greenpau/caddy-auth-portal#google-identity-platform

I guess what you need to do is add a token backend with public keys from your OAuth2.0 provider.

https://github.com/greenpau/caddy-auth-jwt/blob/4a92a4d1891abe337e3e3fd8d00b4e053e2de74c/caddyfile.go#L61-L64

**Comment by greenpau** [comment]
No traction. closing for now.

**Comment by greenpau** [comment]
Reopening the issue. I need to protect Jarvis API ... which uses GRPC ... looks like a similar use case not covered by the current implementation.

**Comment by greenpau** [comment]
FMI, example of GRPC client/server: https://towardsdatascience.com/grpc-in-golang-bb40396eb8b1

**Comment by thatnerdjosh** [comment]
@greenpau I'll take a look at this... it'll take a bit of research for me first, because my GRPC experience is severely limited

**Comment by greenpau** [comment]
This feature is working.
