### ISSUE TITLE
feature: `enable claim headers` without requiring authentication

### ISSUE THREAD

**Issue by SvenDowideit** [greenpau/caddy-authorize#56]
I'm trying to have a webservice fronted by caddy that works in either anonymous mode, or _if_ the user has logged in, can use their name, email and roles to add extra bits.

ideally (because these webservices are coded by other people who are in a rush, and are on internal to the cluster virtual networks), it would be nice to just use the claim headers, and for those to be filled in with "anonymous" when not logged in

but, when I add `jwt` (or more) to a route, it forces authentication.

I'm hoping there's just something simple I havn't understood :)

**Comment by greenpau** [comment]
@SvenDowideit , I will pick this up next week. I am working on rewiring plugins and it is a lot to do ;-)

meanwhile, please look at portal’s cookie.go files. It could be that the portal sets certain cookie options that force the browser not to submit them. I would also consider reviewing cookie_domain directive.

**Comment by SvenDowideit** [comment]
oh, i wasn't specific enough - things work ok when the user has logged in (and `jwt.enable claim headers: true`)

what I can't get working, is to be able to have `jwt.enable claim headers: true` without also having caddy-auth return "Unauthorized User"

**Comment by SvenDowideit** [comment]
rewriting - that sounds scary

**Comment by greenpau** [comment]
@SvenDowideit , in this particular case - necessary. The code was not modular enough. Rewrite KMS handling. You can look at the latest commits. will be wiring new KMS code to portal tomorrow. 

In the near future portal will be able signing tokens using multiple keys (HS, RS, ES) based on certain conditions.

**Comment by SvenDowideit** [comment]
yeah, I'm just going to go on leave for 2 weeks, and worry about it later :)

**Comment by greenpau** [comment]
@SvenDowideit , to clarify, you want unauthenticated users to be able to get “guest” token from portal without providing any credentials?

**Comment by greenpau** [comment]
Sounds a lot like “guest” backend ;-)

**Comment by SvenDowideit** [comment]
perhaps - to rephrase, I want to have a way to get whatever token info and claim headers exist for that browser session (including a guest) without forcing auth

**Comment by greenpau** [comment]
@SvenDowideit , you have a user who has a cookie with JWT token, but you don’t see claims passing through to a backend?

have you tried caddy-trace plugin to debug this?

**Comment by greenpau** [comment]
@SvenDowideit , getting back to this. Could you please let me know the following.

When a user arrives at `jwt` plugin.
1. What does the user have? e.g. token or nothing.
2. If it is a token, what are the relevant fields
3. Desired outcome? e.g. no token, automatically grant access as a specific role and add pass header `X-USER`.

**Comment by SvenDowideit** [comment]
back from leave :)

Think of it like the nicest implementation of  shopping cart - 

- non-authed user goes to site, adds things to cart
- user (registers if needed and) auths to see what specials they have
- cart continues as before

internally, I'd prefer if there's a jwt token, and basic fields exist, but tbh, that's something I suspect can work either way

I'd also love the portal to work for anonymous users - but again, that's just icing

**Comment by greenpau** [comment]
@SvenDowideit , I like the idea of a shopping cart :-) It might make sense to add "shopping cart id" as a field in "anonymous" token.

**Comment by greenpau** [comment]
> non-authed user goes to site, adds things to cart

@SvenDowideit , I introduced a new cookie called `AUTHP_SESSION_ID`. Could you use that to tie non-authenticated user to authenticated user?

**Comment by SvenDowideit** [comment]
maybe - I'm about to change jobs tho, so I'm not sure I'll have time to migrate the running systems from the previous code, to your new stuff, and then test this - lots of Docs to write.
