### ISSUE TITLE
feature: handle a change of user roles

### ISSUE THREAD

**Issue by AtomBaf** [greenpau/caddy-authorize#65]
**Describe the issue**

When a token has been generated and authentication is fine, and when some admin setup has been done elsewhere to change the roles of a user, how should we tell the plugin that the auth token should be refreshed?

**Configuration**

Any caddyfile like this one : https://github.com/greenpau/caddy-auth-jwt#caddyfile

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.3.0
http.authentication.hashes.scrypt v2.3.0
http.authentication.providers.http_basic v2.3.0
http.authentication.providers.jwt v1.2.3
http.handlers.authentication v2.3.0
```

**Expected behavior**

When an admin changes roles of a user, there should be a way to tell the plugin that every token for that user should now be refreshed. JWT token contains a state of all roles, and we should not have to wait the token expiry for the new roles to be updated.

**Additional context**

I don't know how this could be handled exactly. I have a side-car auth app which is today creating the JWT token for the user, along with its roles. When an admin change the roles, I would perform http requests to the plugin so it could consider all previous tokens as expired.
Another way would be, instead of putting roles inside the user jwt token, to directly put the username in the token claims. And on the caddy route side, to put all the allowed users (instead of roles) in the `access_list.values` property. This way, I would only have to change the routes with the caddy API endpoint.

Do you have any more idea?

Thanks for your help

**Comment by greenpau** [comment]
@AtomBaf, I would need to provide an API endpoint you to invalidate specific tokens.

For example, if token matches some condition and it is older than X minutes ago, then invalidate the token. It would be a "block list". Currently, I have the facilities to accomplish this.

**Comment by AtomBaf** [comment]
that sounds perfect!

**Comment by greenpau** [comment]
@AtomBaf , please reopen in https://github.com/greenpau/caddy-security/issues if this is still relevant.
