### ISSUE TITLE
feature: add integration with Open Policy Agent (OPA)

### ISSUE THREAD

**Issue by maxott** [greenpau/caddy-authorize#73]
Hi, I was wondering if it would be possible to delegate autz decisions to OPA similar to https://klotzandrew.com/blog/authorization-with-open-policy-agent?

Thanks

**Comment by greenpau** [comment]
@maxott , post token validation, ask for authorization from OPA server? If so, then it is doable.

Also, I was actually thinking of adding various backends, e.g. RADIUS. If true, then it is related thinking.

**Comment by maxott** [comment]
Great. Where would that plug in. Just curious to learn a bit more about all this works

**Comment by greenpau** [comment]
> Great. Where would that plug in. Just curious to learn a bit more about all this works

@maxott , after the plugin authenticates a user by looking at the user's token, the plugin could pass the properties of a request to OPA server, e.g. method, path, user (if any), user agent, etc.

I am mocking the future interface. The plugin will authorize users using one of the following methods: basic auth, JWT tokens, API key (e.g. X-Token). Next it would `authorize with opa` at the address `http://opa-server-address/path/to/authorize`

```
route /api* {
  authz {
    authenticate with basic jwt api
    config basic ...
    config jwt ...
    config api
    authorize with opa
    config opa http://opa-server-address/path/to/authorize
  }
}
```

Main thing, I want to expand from `jwt` to all sort of mechanisms to authorize users.
