### ISSUE TITLE
question: High Availability

### ISSUE THREAD

**Issue by lbreitk** [greenpau/caddy-authorize#78]
I don't know much about JWT, so I'm just wondering - how will this work if I have multiple instances of caddy using the same config? Will a JWT token issued by instance 1 work if the user gets load balanced to instance 2?

**Comment by jaedle** [comment]
Just make sure to sign the JWT with the same secret (Key/Passphrase), then everything should be fine.

Afaik this plug-in is stateless. Even a restart of your caddy server should be no problem as the token verification is solely done based on the token sent and not on any state.

As JWT are used for authentication purposes on high scale systems (i.e. google auth) this should be no problem 🙃

**Comment by lbreitk** [comment]
awesome, thanks for the quick explanation! That's good to know :)

**Comment by jaedle** [comment]
I’m just a user. I guess @greenpau can give more insight.

**Comment by greenpau** [comment]
@jaedle , thank you for your help!

@lbreitk , i will attempt recording a Youtube video with an explanation.

**Comment by lbreitk** [comment]
You guys are the best, thanks :)

**Comment by greenpau** [comment]
Closing this issue. It is related to https://github.com/greenpau/caddy-authorize/issues/64. Generally speaking, there is a way to configure `caddy` to load keys from a shared source, i.e. can share it via:

- Local File System
- AWS DynamoDB
- AWS S3
- Redis
- Hashicorp Consul

I am working towards making this a reality in `caddy-authorize` plugin.
