### ISSUE TITLE
feature: custom claims conditions

### ISSUE THREAD

**Issue by lorenzodonini** [greenpau/caddy-authorize#79]
**Describe the issue**

Hey and thanks for developing this plugin, great job!

While upgrading from the old [caddy-jwt](https://github.com/BTBurke/caddy-jwt) plugin, I realized that the new plugin does not offer ACL conditions for [custom claims](https://auth0.com/docs/tokens/json-web-tokens/json-web-token-claims#custom-claims).

The snippet I pasted below won't work, as ACLs currently rely on a [whitelist of claim fields](https://github.com/greenpau/caddy-auth-jwt/blob/main/pkg/acl/condition.go#L28). Anything else will throw an error:
```
invalid condition syntax, unsupported field: organization_role, condition: exact match organization_role owner"
```

**Configuration**

```
(access_org_owner) {
	jwt {
		acl rule {
			comment allow access to organization owners
			exact match organization_role owner
			allow stop log error
		}
	}
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.14
```

**Expected behavior**

I think offering the possibility to perform arbitrary checks on custom JWT claims (not just roles, groups, ...) would be a major addition to this plugin (as I mentioned, this was possible with the v1 plugin).

Is this planned (or possible already)? I'm willing to help out and create a PR for this feature.

**Comment by greenpau** [comment]
@lorenzodonini , thank you for opening the issue!

This is a good issue to raise! It comes down that caddy-auth-jwt relies on an external library to perform token signing and verification. As part of the verification, the data is being unpacked to usr.User.Claims that does not support arbitrary fields. I want to keep that data structure. I have no control of the external library's API. So … need creating my own API. I am still weight on potential solution.

**Comment by lorenzodonini** [comment]
Yes, I've been looking through the source code and noticed that you are unpacking the claims into your own data structure.

I see that you are retaining the `app_metadata` field entirely https://github.com/greenpau/caddy-auth-jwt/blob/6e61653f032f45d8b44614a942af33df259d58a7/pkg/user/user.go#L102.
So maybe, if a field is not found within the `inputDataTypes`, as a fallback you could look for custom fields in there. 
This relies on the `app_metadata` field being there, so not a perfect solution, but maybe low-effort? 

Potentially you could also just keep the raw claims struct and somehow pass it around (even an additional `Raw map[string]interface{}` field in  the `Claims` struct would do). That way you would have access to all raw data, as long as you have access to the user object.

Just throwing some ideas on the table. Let me know if you have a better one, or if I can help somehow.

**Comment by greenpau** [comment]
@lorenzodonini , i created and commented out some code in the preparation for the support of non-standard (arbitrary claims). It is in user.go. Stay tuned.

**Comment by greenpau** [comment]
@lorenzodonini , how is your experience with the plugin so far? Are you still using it?

**Comment by lorenzodonini** [comment]
@greenpau Yes I'm still using the plugin (in production as well). I managed to make do without the support for custom claims so far, but it would still be a very appreciated feature.

**Comment by greenpau** [comment]
> @greenpau Yes I'm still using the plugin (in production as well). I managed to make do without the support for custom claims so far, but it would still be a very appreciated feature.

@lorenzodonini , will make it a priority 👍

**Comment by greenpau** [comment]
Created starter configuration in preparation for the implementation: https://gist.github.com/greenpau/0da35620e00c0170cba1d69e12912429

**Comment by greenpau** [comment]
Closed. All future development happens in https://github.com/greenpau/caddy-security/issues/6
