### ISSUE TITLE
IPv6 address truncation in JWT

### ISSUE THREAD

**Issue by timokroeger** [greenpau/caddy-authorize#84]
**Describe the issue**

From the '/whoami' page
```json
{
  "addr": "[2a01",
  "authenticated": true,
  "exp": 1633459456,
```

**Version Information**

```
http.authentication.hashes.bcrypt v2.4.5
http.authentication.hashes.scrypt v2.4.5
http.authentication.providers.http_basic v2.4.5
http.handlers.authentication v2.4.5
http.authentication.providers.jwt v1.3.16
http.handlers.authp v1.4.24
```

**Expected behavior**

Full IPv6 address available in the token.

**Comment by greenpau** [comment]
@timokroeger , thank you for the issue! 👍

**Comment by greenpau** [comment]
Note: need to look into `GetSourceAddress()` from `pkg/utils/address.go`. This is what populates the `addr` field in the token.

**Comment by greenpau** [comment]
@timokroeger , please test with the new release https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.4.26

**Comment by greenpau** [comment]
@timokroeger , found the issue in `portal` and fixed it. please test it with v1.4.27 of `portal`.

**Comment by timokroeger** [comment]
v1.4.27 fixes the issue. I can see the correct IPv6 address, thank you!

**Comment by greenpau** [comment]
@timokroeger , thank you for testing! 👍
