### ISSUE TITLE
breakfix: Roles with spaces in their name are ignored.

### ISSUE THREAD

**Issue by rochdev** [greenpau/caddy-authorize#91]
**Describe the issue**

Using roles with a space in their name results in the role being ignored and Caddy reporting `user role is valid, but not allowed by access list`. It's unclear if spaces are replaced by another character by this plugin. I tried without the space and got the same result.

**Configuration**

Paste full `Caddyfile` below:

```
# irrelevant configuration was either removed or redacted

*.REDACTED {
  @foo host REDACTED
  route @foo {
    authorize {
      allow roles Admin "Super User"
    }

    reverse_proxy foo:3333
  }

  @bar host REDACTED
  route @bar {
    authorize {
      primary yes
      set token sources cookie
      crypto default token name REDACTED
      crypto key sign-verify from env JWT_SECRET
      allow roles Admin
    }

    reverse_proxy bar:3334
  }
}

```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.5
http.authentication.hashes.scrypt v2.4.5
http.authentication.providers.http_basic v2.4.5
http.handlers.authentication v2.4.5
http.authentication.providers.authorize v1.3.18
```

**Expected behavior**

Using roles with a space in them should work properly.

**Comment by greenpau** [comment]
@rochdev , I may have fixed it in the latest release. Please test.
