### ISSUE TITLE
inject header doesn't work

### ISSUE THREAD

**Issue by helmut72** [greenpau/caddy-authorize#94]
**Describe the issue**

`inject header` doesn't work. Standard output looks good, using whoami (docker container):

```
X-Token-Subject: testuser
X-Token-User-Email: testuser@testdomain.com
X-Token-User-Name: Test User
X-Token-User-Roles: app1 app2 app3
```

**Relevant Configuration**

```
route {
    authorize {
        ...
        inject headers with claims
        inject header "Remote-User" from field_name
    }
    reverse_proxy http://ip_to_whoami:port {
        import backend_headers 443
    }
}
```

backend_headers:
```
(backend_headers) {
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-Port {args.0}
        header_up X-Forwarded-Host {host}
}
```

I've read:
https://authp.github.io/docs/authorize/headers

Also read this discussion, which looks the same what I want to do:
https://github.com/greenpau/caddy-authorize/issues/85#issuecomment-937952132

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.6
http.authentication.hashes.scrypt v2.4.6
http.authentication.providers.http_basic v2.4.6
http.handlers.authentication v2.4.6
caddy.logging.encoders.filter.basic_auth_user v1.0.0
http.authentication.providers.authorize v1.3.22
http.handlers.authp v1.4.36
```

**Expected behavior**

Inject some additional headers from variables.

**Additional context**

I have tried as field_name: `username`, `sAMAccountName`, `user`, `X-Token-Subject` and `subject`. There is even no empty Remote-User header send to whoami.

Thank you!

**Comment by helmut72** [comment]
I need to use `sub` for the username.

**Comment by greenpau** [comment]
@helmut72 , have you tried the below?

inject header "Remote-User" from sub

**Comment by helmut72** [comment]
Yes, this is what I found and what I mean with "I need to use `sub` for the username".
