### ISSUE TITLE
feature: Accept a login hint in the Caddyfile's authorize block

### ISSUE THREAD

**Issue by PedroDBFlores** [greenpau/caddy-authorize#96]
For some OAuth2 providers, there is a possibility of providing a login_hint parameter that will prefill the user's login on that provider (usually email).

For some routes I would like to be able to send the user to a login page with it's email prefilled, for this I thought of adding a set login hint my_hint parameter to the authorize block on the Caddyfile. The idea is that this login hint is then forwarded to the authorizer, and handled there.

I've opened a PR [here](https://github.com/greenpau/caddy-authorize/pull/95) with the required changes. And the relevant issue/PR is also created on caddy-auth-portal.

**Comment by greenpau** [comment]
>  When looking at other commands (like crypto key my_id verify from env foo), it seems like we might also implement the syntax of this new command like set login hint from <cookie|query> foo. Do you have a preference here?

@PedroDBFlores , @lennartschoch , I think the best way to handle this is to pass `login_hint` via query parameter only. To enable the feature, user `enable login hint` Caddyfile directive. 

If the feature is enabled AND login hint is not in query parameters AND the user provided a valid token token AND the token provided by a user is expired, THEN extract the email address from the expired token and pass it to `login_hint`.

You can catch the error in here:

https://github.com/greenpau/caddy-authorize/blob/07ab869315d9e0d9085a554d8d5f4fd5b4d705d8/pkg/authz/authorizer.go#L137-L172

The verification of the token happens here. You just need to play around with it.

https://github.com/greenpau/caddy-authorize/blob/07ab869315d9e0d9085a554d8d5f4fd5b4d705d8/pkg/validator/sources.go#L177-L184

Additionally, please create create a function that would verify that login hint is a valid email or domain name (in `pkg/utils/validate` directory).

**Comment by greenpau** [comment]
@PedroDBFlores , @lennartschoch ,

The `usr, err := m.tokenValidator.Authorize(ctx, r)` may return an error, but it can have non nil-usr too!!!

Note how `usr.Authenticator.URL` is used to determine who originally authenticated a user.

https://github.com/greenpau/caddy-authorize/blob/07ab869315d9e0d9085a554d8d5f4fd5b4d705d8/pkg/authz/authorizer.go#L188-L189

Similarly, you can do the same thing to extract email from an expired token. 

https://github.com/greenpau/caddy-authorize/blob/07ab869315d9e0d9085a554d8d5f4fd5b4d705d8/pkg/kms/keystore.go#L258-L264

https://github.com/greenpau/caddy-authorize/blob/07ab869315d9e0d9085a554d8d5f4fd5b4d705d8/pkg/kms/keystore.go#L277-L281

**Comment by lennartschoch** [comment]
Thanks for the quick response, @greenpau!

I like that approach! :)

The only thing I am not sure about is the validation:
According to the [OpenID Connect standard](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1), `login_hint` can be any sort of identifier (for example also a phone number or even the `sub` as implemented by [Google](https://developers.google.com/identity/protocols/oauth2/openid-connect#sendauthrequest)), so I am a bit afraid we'd be introducing unnecessary restrictions.

This also makes me think whether we should separate the forwarding of the `login_hint` query param and the extraction of login hints from expired tokens. Automatically setting the login hint from expired tokens whenever the `enable login hint` command is set might cause issues for developers that want to use the login hint with another value than the users email address. Any thoughts on this?

**Comment by greenpau** [comment]
>  According to the OpenID Connect standard, login_hint can be any sort of identifier (for example also a phone number or even the sub as implemented by Google), so I am a bit afraid we'd be introducing unnecessary restrictions.

@lennartschoch , I treat `login_hint` as an input. What am I concerned about? Primarily phishing and the ability to abuse this interface. Consider `?redirect_url=http://auth.contoso.com&login_hint=foo@bar.com%26redirect_url%3Dhttp%3A%2F%2Fbadactor`. If not parsed/validated correctly, a user may end up at `http://badactor`.

@PedroDBFlores, please implement the following:

* add `LoginHintValidators`

```
type Authorizer struct {
  LoginHint                   string                      `json:"login_hint,omitempty" xml:"login_hint,omitempty" yaml:"login_hint,omitempty"`
  LoginHintValidators []string `json:"login_hint_validators,omitempty" xml:"login_hint_validators,omitempty" yaml:"login_hint_validators,omitempty"`
```

* pass `login_hint_validators` via `redirOpts`

```
redirOpts["login_hint_validators"] = m.LoginHintValidators
```

* support the following Caddyfile syntax (an test it

```
enable login hint [with [email] [phone] [alphanumeric]]
```

This allows:

```
# default validator: alphanumeric + `-`, + `.`, etc. The gist - do not allow encoding (e.g. `%`)
enable login hint

# validate the login hint is an email
enable login hint with email

# validate the login hint is either email or phone
enable login hint with email phone

# validate the login hint is an alphanumeric string (think username)
enable login hint with alphanumeric
```

**Comment by greenpau** [comment]
@PedroDBFlores @lennartschoch , fyi https://github.com/greenpau/caddy-authorize/commit/544ab8caf8fd381d9e2ff31ba0629dbbdf01592a

**Comment by PedroDBFlores** [comment]
Thanks for the attention, I've merged that commit into my current branch. One question though, why pass the `login_hint_validators` to `redirOpts`? Wouldn't that mean that caddy_auth_portal should be the one validating them then?

**Comment by greenpau** [comment]
> why pass the login_hint_validators to redirOpts?

@PedroDBFlores , you are correct! 👍  You have them in `func (m Authorizer) handleLoginHint(` via `m.LoginHintValidators`.

**Comment by greenpau** [comment]
@PedroDBFlores , the `redirOpts` is just a container to store things in. Think of it as `context` in HTTP handlers. I just don't use the `context` 😃

**Comment by PedroDBFlores** [comment]
Cool, I've made some more changes and tried to reorganize it a bit better. I ask that you also take a good look at the validators, do you think that we should go further into the regex rules?

**Comment by greenpau** [comment]
> I ask that you also take a good look at the validators, do you think that we should go further into the regex rules?

@PedroDBFlores , good enough! 👍 

---

Also, I think you are missing a critical component in your PR. I rather you guessing it (let me know if you want me to tell it), but will give you two hints:

1. If you have multiple `authorize` clauses in the same `context`, which one is primary? https://authp.github.io/docs/authorize/arch
2. Why do you call the field `LoginHintEnabled` and not `LoginHintDisabled`?

**Comment by PedroDBFlores** [comment]
I've understood now that we can enable it but not disable it explicitly, so I thought of the following?

```
set login hint <enabled <with [email | phone | alphanumeric]> | disabled>

# to enable login hint with all validators (by default)
set login hint enabled

# to enable login hint with email validation only
set login hint enabled with email

# to disable login hint
set login hint disabled
```

And by default an `authorize` clause would consider login hint to be disabled.

**Comment by greenpau** [comment]
@PedroDBFlores , see https://github.com/greenpau/caddy-authorize/blob/544ab8caf8fd381d9e2ff31ba0629dbbdf01592a/pkg/authz/manager.go#L137. How would you change the code now?

**Comment by greenpau** [comment]
This one is even better explains it: https://github.com/greenpau/caddy-authorize/blob/544ab8caf8fd381d9e2ff31ba0629dbbdf01592a/pkg/authz/manager.go#L155

**Comment by greenpau** [comment]
@PedroDBFlores , in short, you can see if login hint is enabled by the number of validators associated with it.

**Comment by lennartschoch** [comment]
I just pushed the commit that enables inheriting of the login hint config from the primary instance, could you have a look @greenpau? :)

I was wondering about one more thing: Since we pass the login hint by calling a route like `/protected?login=hint=foo@bar.com`, the login hint will be taken to the `redirect_url`. Is this something we should mitigate?

**Comment by lennartschoch** [comment]
I've created a PR that removes the login hint from the redirect URL [here](https://github.com/greenpau/caddy-auth-portal/pull/225).
